//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanRivalsManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrbanRivalsManager.Properties.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have initiative? (i.e. Courage on first turn).
        /// </summary>
        public static string ui_calculator_firstplayer {
            get {
                return ResourceManager.GetString("ui_calculator_firstplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode: .
        /// </summary>
        public static string ui_calculator_gamemode {
            get {
                return ResourceManager.GetString("ui_calculator_gamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Combat.
        /// </summary>
        public static string ui_calculator_new_combat {
            get {
                return ResourceManager.GetString("ui_calculator_new_combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Random active?.
        /// </summary>
        public static string ui_calculator_random {
            get {
                return ResourceManager.GetString("ui_calculator_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Combat.
        /// </summary>
        public static string ui_calculator_start_combat {
            get {
                return ResourceManager.GetString("ui_calculator_start_combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and the app needs to be closed. 
        ///IS NOT your fault, is ours. 
        ///But you can help us fix this problem with two simple steps:
        ///1) Fill the form below. No field is compulsory, you can leave them blank is you don&apos;t know what to write.
        ///2) Hit the Submit button.
        ///Thanks you!.
        /// </summary>
        public static string ui_error_sendlog_disclaimer {
            get {
                return ResourceManager.GetString("ui_error_sendlog_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string ui_error_sendlog_email {
            get {
                return ResourceManager.GetString("ui_error_sendlog_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the first time that the app crashes this way?.
        /// </summary>
        public static string ui_error_sendlog_firsttime {
            get {
                return ResourceManager.GetString("ui_error_sendlog_firsttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ui_error_sendlog_name {
            get {
                return ResourceManager.GetString("ui_error_sendlog_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations and other information that you think could be relevant..
        /// </summary>
        public static string ui_error_sendlog_observations {
            get {
                return ResourceManager.GetString("ui_error_sendlog_observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include your name and email. You can leave it empty.
        ///We will use this info to contact with you to speed up the fix of the error, or send you a notification when an update that fixes the bug is available..
        /// </summary>
        public static string ui_error_sendlog_personalinfo {
            get {
                return ResourceManager.GetString("ui_error_sendlog_personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you retrace your steps before the crash? 
        ///If you can reproduce it or think about how it happened write it step by step..
        /// </summary>
        public static string ui_error_sendlog_retracesteps {
            get {
                return ResourceManager.GetString("ui_error_sendlog_retracesteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string ui_gamemode_classic {
            get {
                return ResourceManager.GetString("ui_gamemode_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ui_gamemode_custom {
            get {
                return ResourceManager.GetString("ui_gamemode_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel.
        /// </summary>
        public static string ui_gamemode_duel {
            get {
                return ResourceManager.GetString("ui_gamemode_duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELO.
        /// </summary>
        public static string ui_gamemode_elo {
            get {
                return ResourceManager.GetString("ui_gamemode_elo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaderWars.
        /// </summary>
        public static string ui_gamemode_leaderwars {
            get {
                return ResourceManager.GetString("ui_gamemode_leaderwars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        public static string ui_gamemode_solo {
            get {
                return ResourceManager.GetString("ui_gamemode_solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        public static string ui_gamemode_survivor {
            get {
                return ResourceManager.GetString("ui_gamemode_survivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourney.
        /// </summary>
        public static string ui_gamemode_tourney {
            get {
                return ResourceManager.GetString("ui_gamemode_tourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ui_general_accept {
            get {
                return ResourceManager.GetString("ui_general_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ui_general_cancel {
            get {
                return ResourceManager.GetString("ui_general_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ui_general_exit {
            get {
                return ResourceManager.GetString("ui_general_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ui_general_no {
            get {
                return ResourceManager.GetString("ui_general_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ui_general_yes {
            get {
                return ResourceManager.GetString("ui_general_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        public static string ui_playerstatus_confidence {
            get {
                return ResourceManager.GetString("ui_playerstatus_confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courage.
        /// </summary>
        public static string ui_playerstatus_courage {
            get {
                return ResourceManager.GetString("ui_playerstatus_courage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal: (value/max).
        /// </summary>
        public static string ui_playerstatus_heal {
            get {
                return ResourceManager.GetString("ui_playerstatus_heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life:.
        /// </summary>
        public static string ui_playerstatus_life {
            get {
                return ResourceManager.GetString("ui_playerstatus_life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillz:.
        /// </summary>
        public static string ui_playerstatus_pillz {
            get {
                return ResourceManager.GetString("ui_playerstatus_pillz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison: (value/min).
        /// </summary>
        public static string ui_playerstatus_poison {
            get {
                return ResourceManager.GetString("ui_playerstatus_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprisal.
        /// </summary>
        public static string ui_playerstatus_reprisal {
            get {
                return ResourceManager.GetString("ui_playerstatus_reprisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenge.
        /// </summary>
        public static string ui_playerstatus_revenge {
            get {
                return ResourceManager.GetString("ui_playerstatus_revenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string ui_roundresults_attack {
            get {
                return ResourceManager.GetString("ui_roundresults_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        public static string ui_roundresults_heal {
            get {
                return ResourceManager.GetString("ui_roundresults_heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        public static string ui_roundresults_poison {
            get {
                return ResourceManager.GetString("ui_roundresults_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power / Damage.
        /// </summary>
        public static string ui_roundresults_powerdamage {
            get {
                return ResourceManager.GetString("ui_roundresults_powerdamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives Outcome.
        /// </summary>
        public static string ui_roundresults_resultlives {
            get {
                return ResourceManager.GetString("ui_roundresults_resultlives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillz Outcome.
        /// </summary>
        public static string ui_roundresults_resultpillz {
            get {
                return ResourceManager.GetString("ui_roundresults_resultpillz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Pillz.
        /// </summary>
        public static string ui_roundresults_usedpillz {
            get {
                return ResourceManager.GetString("ui_roundresults_usedpillz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Winner.
        /// </summary>
        public static string ui_roundresults_winner {
            get {
                return ResourceManager.GetString("ui_roundresults_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: .
        /// </summary>
        public static string ui_searchbox_level {
            get {
                return ResourceManager.GetString("ui_searchbox_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, min {0} char(s).
        /// </summary>
        public static string ui_searchcard_defaulttext {
            get {
                return ResourceManager.GetString("ui_searchcard_defaulttext", resourceCulture);
            }
        }
    }
}
