//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanRivalsCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrbanRivalsCore.Properties.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string card_rarity_collector {
            get {
                return ResourceManager.GetString("card_rarity_collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string card_rarity_common {
            get {
                return ResourceManager.GetString("card_rarity_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        public static string card_rarity_legendary {
            get {
                return ResourceManager.GetString("card_rarity_legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string card_rarity_rare {
            get {
                return ResourceManager.GetString("card_rarity_rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebirth.
        /// </summary>
        public static string card_rarity_rebirth {
            get {
                return ResourceManager.GetString("card_rarity_rebirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string card_rarity_uncommon {
            get {
                return ResourceManager.GetString("card_rarity_uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stars.
        /// </summary>
        public static string clan_name_allstars {
            get {
                return ResourceManager.GetString("clan_name_allstars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangers.
        /// </summary>
        public static string clan_name_bangers {
            get {
                return ResourceManager.GetString("clan_name_bangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berzerk.
        /// </summary>
        public static string clan_name_berzerk {
            get {
                return ResourceManager.GetString("clan_name_berzerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fang Pi Clang.
        /// </summary>
        public static string clan_name_fangpiclang {
            get {
                return ResourceManager.GetString("clan_name_fangpiclang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freaks.
        /// </summary>
        public static string clan_name_freaks {
            get {
                return ResourceManager.GetString("clan_name_freaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozn.
        /// </summary>
        public static string clan_name_frozn {
            get {
                return ResourceManager.GetString("clan_name_frozn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHEIST.
        /// </summary>
        public static string clan_name_gheist {
            get {
                return ResourceManager.GetString("clan_name_gheist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huracan.
        /// </summary>
        public static string clan_name_huracan {
            get {
                return ResourceManager.GetString("clan_name_huracan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungo.
        /// </summary>
        public static string clan_name_jungo {
            get {
                return ResourceManager.GetString("clan_name_jungo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junkz.
        /// </summary>
        public static string clan_name_junkz {
            get {
                return ResourceManager.GetString("clan_name_junkz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Junta.
        /// </summary>
        public static string clan_name_lajunta {
            get {
                return ResourceManager.GetString("clan_name_lajunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string clan_name_leader {
            get {
                return ResourceManager.GetString("clan_name_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montana.
        /// </summary>
        public static string clan_name_montana {
            get {
                return ResourceManager.GetString("clan_name_montana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        public static string clan_name_nightmare {
            get {
                return ResourceManager.GetString("clan_name_nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piranas.
        /// </summary>
        public static string clan_name_piranas {
            get {
                return ResourceManager.GetString("clan_name_piranas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pussycats.
        /// </summary>
        public static string clan_name_pussycats {
            get {
                return ResourceManager.GetString("clan_name_pussycats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue.
        /// </summary>
        public static string clan_name_rescue {
            get {
                return ResourceManager.GetString("clan_name_rescue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roots.
        /// </summary>
        public static string clan_name_roots {
            get {
                return ResourceManager.GetString("clan_name_roots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakrohm.
        /// </summary>
        public static string clan_name_sakrohm {
            get {
                return ResourceManager.GetString("clan_name_sakrohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel.
        /// </summary>
        public static string clan_name_sentinel {
            get {
                return ResourceManager.GetString("clan_name_sentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeelz.
        /// </summary>
        public static string clan_name_skeelz {
            get {
                return ResourceManager.GetString("clan_name_skeelz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulu Watu.
        /// </summary>
        public static string clan_name_uluwatu {
            get {
                return ResourceManager.GetString("clan_name_uluwatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppers.
        /// </summary>
        public static string clan_name_uppers {
            get {
                return ResourceManager.GetString("clan_name_uppers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vortex.
        /// </summary>
        public static string clan_name_vortex {
            get {
                return ResourceManager.GetString("clan_name_vortex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: Courage: Power +3, Max 10.
        /// </summary>
        public static string skill_leader_ambre {
            get {
                return ResourceManager.GetString("skill_leader_ambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: Strike Back.
        /// </summary>
        public static string skill_leader_ashigaru {
            get {
                return ResourceManager.GetString("skill_leader_ashigaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: +1 Life Per Round.
        /// </summary>
        public static string skill_leader_bridget {
            get {
                return ResourceManager.GetString("skill_leader_bridget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: -1 Opp Pillz Per Round, Min 3.
        /// </summary>
        public static string skill_leader_eklore {
            get {
                return ResourceManager.GetString("skill_leader_eklore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: -1 Opp Power, Min 5.
        /// </summary>
        public static string skill_leader_eyrik {
            get {
                return ResourceManager.GetString("skill_leader_eyrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: +6 Attack.
        /// </summary>
        public static string skill_leader_hugo {
            get {
                return ResourceManager.GetString("skill_leader_hugo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: Defeat: Recover 1 Pillz Out Of 3.
        /// </summary>
        public static string skill_leader_melody {
            get {
                return ResourceManager.GetString("skill_leader_melody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: +1 Pillz Per Round, Max 10.
        /// </summary>
        public static string skill_leader_morphun {
            get {
                return ResourceManager.GetString("skill_leader_morphun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie-break.
        /// </summary>
        public static string skill_leader_solomon {
            get {
                return ResourceManager.GetString("skill_leader_solomon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: Damage +1.
        /// </summary>
        public static string skill_leader_timber {
            get {
                return ResourceManager.GetString("skill_leader_timber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: Xp +90%.
        /// </summary>
        public static string skill_leader_vansaar {
            get {
                return ResourceManager.GetString("skill_leader_vansaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team: -2 Opp Damage, Min 4.
        /// </summary>
        public static string skill_leader_vholt {
            get {
                return ResourceManager.GetString("skill_leader_vholt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ability.
        /// </summary>
        public static string skill_no_ability {
            get {
                return ResourceManager.GetString("skill_no_ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bonus.
        /// </summary>
        public static string skill_no_bonus {
            get {
                return ResourceManager.GetString("skill_no_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability unlocked at level {0}.
        /// </summary>
        public static string skill_not_unlocked {
            get {
                return ResourceManager.GetString("skill_not_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlash: .
        /// </summary>
        public static string skill_prefix_backlash {
            get {
                return ResourceManager.GetString("skill_prefix_backlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawl: .
        /// </summary>
        public static string skill_prefix_brawl {
            get {
                return ResourceManager.GetString("skill_prefix_brawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence: .
        /// </summary>
        public static string skill_prefix_confidence {
            get {
                return ResourceManager.GetString("skill_prefix_confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courage: .
        /// </summary>
        public static string skill_prefix_courage {
            get {
                return ResourceManager.GetString("skill_prefix_courage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat: .
        /// </summary>
        public static string skill_prefix_defeat {
            get {
                return ResourceManager.GetString("skill_prefix_defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrowth: .
        /// </summary>
        public static string skill_prefix_degrowth {
            get {
                return ResourceManager.GetString("skill_prefix_degrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer: .
        /// </summary>
        public static string skill_prefix_equalizer {
            get {
                return ResourceManager.GetString("skill_prefix_equalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth: .
        /// </summary>
        public static string skill_prefix_growth {
            get {
                return ResourceManager.GetString("skill_prefix_growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killshot: .
        /// </summary>
        public static string skill_prefix_killshot {
            get {
                return ResourceManager.GetString("skill_prefix_killshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprisal: .
        /// </summary>
        public static string skill_prefix_reprisal {
            get {
                return ResourceManager.GetString("skill_prefix_reprisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenge: .
        /// </summary>
        public static string skill_prefix_revenge {
            get {
                return ResourceManager.GetString("skill_prefix_revenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop: .
        /// </summary>
        public static string skill_prefix_stop {
            get {
                return ResourceManager.GetString("skill_prefix_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support: .
        /// </summary>
        public static string skill_prefix_support {
            get {
                return ResourceManager.GetString("skill_prefix_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory or Defeat: .
        /// </summary>
        public static string skill_prefix_victory_or_defeat {
            get {
                return ResourceManager.GetString("skill_prefix_victory_or_defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Attack Modifier.
        /// </summary>
        public static string skill_suffix_cancel_attack_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_attack_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Damage Modifier.
        /// </summary>
        public static string skill_suffix_cancel_damage_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_damage_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Leader.
        /// </summary>
        public static string skill_suffix_cancel_leader {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Life Modifier.
        /// </summary>
        public static string skill_suffix_cancel_life_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_life_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Pillz And Life Modifier.
        /// </summary>
        public static string skill_suffix_cancel_pillz_and_life_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_pillz_and_life_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Pillz Modifier.
        /// </summary>
        public static string skill_suffix_cancel_pillz_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_pillz_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Power And Damage Modifier.
        /// </summary>
        public static string skill_suffix_cancel_power_and_damage_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_power_and_damage_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Opp Power Modifier.
        /// </summary>
        public static string skill_suffix_cancel_power_modifier {
            get {
                return ResourceManager.GetString("skill_suffix_cancel_power_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consume {0}, Min {1}.
        /// </summary>
        public static string skill_suffix_consume_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_consume_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Opp Bonus.
        /// </summary>
        public static string skill_suffix_copy_bonus {
            get {
                return ResourceManager.GetString("skill_suffix_copy_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Opp Damage.
        /// </summary>
        public static string skill_suffix_copy_damage {
            get {
                return ResourceManager.GetString("skill_suffix_copy_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Opp Power.
        /// </summary>
        public static string skill_suffix_copy_power {
            get {
                return ResourceManager.GetString("skill_suffix_copy_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Opp Power And Damage.
        /// </summary>
        public static string skill_suffix_copy_power_and_damage {
            get {
                return ResourceManager.GetString("skill_suffix_copy_power_and_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Attack, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_attack_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_attack_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Attack Per Life Left, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_attack_x_per_remaining_life_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_attack_x_per_remaining_life_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Attack Per Pillz Left, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_attack_x_per_remaining_pillz_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_attack_x_per_remaining_pillz_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Damage, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_damage_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_damage_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Life, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_life_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_life_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Life, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_life_x_min_y_backlash {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_life_x_min_y_backlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Pillz, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_pillz_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_pillz_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Pillz, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_pillz_x_min_y_backlash {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_pillz_x_min_y_backlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Power And Damage, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_power_and_damage_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_power_and_damage_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} Opp Power, Min {1}.
        /// </summary>
        public static string skill_suffix_decrease_power_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_decrease_power_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dope {0}, Max {1}.
        /// </summary>
        public static string skill_suffix_dope_x_max_y {
            get {
                return ResourceManager.GetString("skill_suffix_dope_x_max_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Exchange.
        /// </summary>
        public static string skill_suffix_exchange_damage {
            get {
                return ResourceManager.GetString("skill_suffix_exchange_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Exchange.
        /// </summary>
        public static string skill_suffix_exchange_power {
            get {
                return ResourceManager.GetString("skill_suffix_exchange_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal {0}, Max {1}.
        /// </summary>
        public static string skill_suffix_heal_x_max_y {
            get {
                return ResourceManager.GetString("skill_suffix_heal_x_max_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +{0}.
        /// </summary>
        public static string skill_suffix_increase_attack_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_attack_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Attack Per Life Left.
        /// </summary>
        public static string skill_suffix_increase_attack_x_per_remaining_life {
            get {
                return ResourceManager.GetString("skill_suffix_increase_attack_x_per_remaining_life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Attack Per Pillz Left.
        /// </summary>
        public static string skill_suffix_increase_attack_x_per_remaining_pillz {
            get {
                return ResourceManager.GetString("skill_suffix_increase_attack_x_per_remaining_pillz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage +{0}.
        /// </summary>
        public static string skill_suffix_increase_damage_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_damage_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Life.
        /// </summary>
        public static string skill_suffix_increase_life_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_life_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Life, Max {1}.
        /// </summary>
        public static string skill_suffix_increase_life_x_max_y {
            get {
                return ResourceManager.GetString("skill_suffix_increase_life_x_max_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Life Per Damage.
        /// </summary>
        public static string skill_suffix_increase_life_x_per_damage {
            get {
                return ResourceManager.GetString("skill_suffix_increase_life_x_per_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Life Per Damage, Max {1}.
        /// </summary>
        public static string skill_suffix_increase_life_x_per_damage_max_y {
            get {
                return ResourceManager.GetString("skill_suffix_increase_life_x_per_damage_max_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Pillz And Life +{0}.
        /// </summary>
        public static string skill_suffix_increase_pillz_and_life_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_pillz_and_life_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Pillz.
        /// </summary>
        public static string skill_suffix_increase_pillz_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_pillz_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Pillz, Max {1}.
        /// </summary>
        public static string skill_suffix_increase_pillz_x_max_y {
            get {
                return ResourceManager.GetString("skill_suffix_increase_pillz_x_max_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Pillz Per Damage.
        /// </summary>
        public static string skill_suffix_increase_pillz_x_per_damage {
            get {
                return ResourceManager.GetString("skill_suffix_increase_pillz_x_per_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power And Damage +{0}.
        /// </summary>
        public static string skill_suffix_increase_power_and_damage_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_power_and_damage_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power +{0}.
        /// </summary>
        public static string skill_suffix_increase_power_x {
            get {
                return ResourceManager.GetString("skill_suffix_increase_power_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infection {0}, Min {1}.
        /// </summary>
        public static string skill_suffix_infection_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_infection_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison {0}, Min {1}.
        /// </summary>
        public static string skill_suffix_poison_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_poison_x_min_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison {0}, Min {1}.
        /// </summary>
        public static string skill_suffix_poison_x_min_y_backlash {
            get {
                return ResourceManager.GetString("skill_suffix_poison_x_min_y_backlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Ability.
        /// </summary>
        public static string skill_suffix_protect_ability {
            get {
                return ResourceManager.GetString("skill_suffix_protect_ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Attack.
        /// </summary>
        public static string skill_suffix_protect_attack {
            get {
                return ResourceManager.GetString("skill_suffix_protect_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Bonus.
        /// </summary>
        public static string skill_suffix_protect_bonus {
            get {
                return ResourceManager.GetString("skill_suffix_protect_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Damage.
        /// </summary>
        public static string skill_suffix_protect_damage {
            get {
                return ResourceManager.GetString("skill_suffix_protect_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Power.
        /// </summary>
        public static string skill_suffix_protect_power {
            get {
                return ResourceManager.GetString("skill_suffix_protect_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Power And Damage.
        /// </summary>
        public static string skill_suffix_protect_power_and_damage {
            get {
                return ResourceManager.GetString("skill_suffix_protect_power_and_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover {0} Pillz Out Of {1}.
        /// </summary>
        public static string skill_suffix_recover_x_pillz_out_of_y {
            get {
                return ResourceManager.GetString("skill_suffix_recover_x_pillz_out_of_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regen {0}, Max {1}.
        /// </summary>
        public static string skill_suffix_regen_x_max_y {
            get {
                return ResourceManager.GetString("skill_suffix_regen_x_max_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Opp Ability.
        /// </summary>
        public static string skill_suffix_stop_ability {
            get {
                return ResourceManager.GetString("skill_suffix_stop_ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Opp Bonus.
        /// </summary>
        public static string skill_suffix_stop_bonus {
            get {
                return ResourceManager.GetString("skill_suffix_stop_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxin {0}, Min {1}.
        /// </summary>
        public static string skill_suffix_toxin_x_min_y {
            get {
                return ResourceManager.GetString("skill_suffix_toxin_x_min_y", resourceCulture);
            }
        }
    }
}
